// Gedeeld sjabloon van de subpagina's: taal, opstart (boot), voetkaart en rekenmodule voor de druknorm.
// Elke pagina definieert zelf window.RENDER (en zo nodig window.POST) en roept daarna boot() aan.
var lang='nl';try{lang=localStorage.getItem('px_lang')||'nl';}catch(e){}
function tr(x){return Array.isArray(x)?(lang==='nl'?x[0]:x[1]):x;}
function setLang(L){lang=L;try{localStorage.setItem('px_lang',L);}catch(e){}}
var REGIONS=[{z:1,c:"#b6c44a",n:["Hallux (grote teen)","Hallux (big toe)"],v:180,ok:1},{z:2,c:"#b6c44a",n:["Tenen 2\u20135","Toes 2\u20135"],v:120,ok:1},{z:3,c:"#e0922f",n:["Metatarsaal 1","Metatarsal 1"],v:265,ok:0},{z:4,c:"#c44a3a",n:["Metatarsaal 2\u20133","Metatarsal 2\u20133"],v:320,ok:0},{z:5,c:"#e0922f",n:["Metatarsaal 4\u20135","Metatarsal 4\u20135"],v:205,ok:0},{z:6,c:"#4f9d69",n:["Mediale middenvoet","Medial midfoot"],v:90,ok:1},{z:7,c:"#4f9d69",n:["Laterale middenvoet","Lateral midfoot"],v:100,ok:1},{z:8,c:"#e0922f",n:["Hiel","Heel"],v:240,ok:0}];
function footMap(){var leg=REGIONS.map(function(R){return '<li data-z="'+R.z+'"><span class="b" style="background:'+R.c+'">'+R.z+'</span><span class="nm">'+tr(R.n)+'</span><span class="vv">'+R.v+'</span><span class="fl '+(R.ok?'pass':'fail')+'">'+(R.ok?'\u2713':'!')+'</span></li>';}).join('');
return '<div class="footwrap"><svg viewBox="0 0 280 470" role="img"><g class="zg" data-z="1"><rect class="zone" x="72" y="56" width="60" height="70" rx="26" fill="#b6c44a"/><text class="znum" x="102" y="86">1</text><text class="zval" x="102" y="104">180</text></g><g class="zg" data-z="2"><rect class="zone" x="140" y="62" width="92" height="58" rx="18" fill="#b6c44a"/><text class="znum" x="186" y="88">2</text><text class="zval" x="186" y="106">120</text></g><g class="zg" data-z="3"><rect class="zone" x="64" y="134" width="56" height="92" rx="15" fill="#e0922f"/><text class="znum" x="92" y="174">3</text><text class="zval" x="92" y="192">265</text></g><g class="zg" data-z="4"><rect class="zone" x="124" y="134" width="56" height="92" rx="15" fill="#c44a3a"/><text class="znum" x="152" y="174">4</text><text class="zval" x="152" y="192">320</text></g><g class="zg" data-z="5"><rect class="zone" x="184" y="134" width="56" height="92" rx="15" fill="#e0922f"/><text class="znum" x="212" y="174">5</text><text class="zval" x="212" y="192">205</text></g><g class="zg" data-z="6"><rect class="zone" x="118" y="234" width="61" height="86" rx="15" fill="#4f9d69"/><text class="znum" x="148" y="273">6</text><text class="zval" x="148" y="291">90</text></g><g class="zg" data-z="7"><rect class="zone" x="179" y="234" width="61" height="86" rx="15" fill="#4f9d69"/><text class="znum" x="210" y="273">7</text><text class="zval" x="210" y="291">100</text></g><g class="zg" data-z="8"><ellipse class="zone" cx="152" cy="392" rx="78" ry="60" fill="#e0922f"/><text class="znum" x="152" y="390">8</text><text class="zval" x="152" y="410">240</text></g></svg><div><ul class="flegend">'+leg+'</ul><div class="scale"><div style="background:#4f9d69">&lt;100</div><div style="background:#b6c44a">100\u2013200</div><div style="background:#e0922f">200\u2013300</div><div style="background:#c44a3a">&gt;300 kPa</div></div></div></div>';}
function wireFoot(){function hot(z,on){document.querySelectorAll('[data-z="'+z+'"]').forEach(function(el){el.classList.toggle('hot',on);});}document.querySelectorAll('.zg,[data-z]').forEach(function(g){if(!g.dataset.z)return;g.addEventListener('mouseenter',function(){hot(g.dataset.z,true)});g.addEventListener('mouseleave',function(){hot(g.dataset.z,false)});});}
function calc(){return '<div class="card calc"><div class="row"><label>'+tr(["Piekdruk zonder CMFO (visite 2)","Peak pressure without CMFO (visit 2)"])+'</label><input type="range" id="cb" min="120" max="600" value="300"><span class="val"><span id="cbv">300</span> kPa</span></div><div class="row"><label>'+tr(["Piekdruk mét CMFO","Peak pressure with CMFO"])+'</label><input type="range" id="cc" min="60" max="600" value="240"><span class="val"><span id="ccv">240</span> kPa</span></div><div class="bar2"><div class="fill" id="cf"></div><div class="thr" style="left:33.3%"></div><div class="thrl" style="left:33.3%">200</div><div class="bmark" id="cm"></div></div><div class="barscale"><span>0</span><span>300</span><span>600 kPa</span></div><div class="out" id="co"><p class="big" id="cob"></p><p id="com" style="margin:0;font-size:13.5px"></p></div></div>';}
function wireCalc(){var b=document.getElementById('cb'),c=document.getElementById('cc');if(!b||!c)return;function u(){var bv=+b.value,cv=+c.value;document.getElementById('cbv').textContent=bv;document.getElementById('ccv').textContent=cv;var red=Math.max(0,Math.round((1-cv/bv)*100)),ok=(cv<200)||(red>=25);var f=document.getElementById('cf');f.style.width=(cv/600*100)+'%';f.style.background=ok?'#2f8f5b':'#c0392b';document.getElementById('cm').style.left=(bv/600*100)+'%';var o=document.getElementById('co');o.className='out '+(ok?'ok':'nok');document.getElementById('cob').textContent=tr(ok?["Doel bereikt \u2713","Goal reached \u2713"]:["Doel nog niet bereikt","Goal not yet reached"]);document.getElementById('com').textContent=tr(["Reductie","Reduction"])+': '+red+'% \u00b7 '+cv+' kPa';}b.addEventListener('input',u);c.addEventListener('input',u);u();}
function boot(){var app=document.getElementById("app");function paint(){document.documentElement.lang=lang;app.innerHTML=window.RENDER();var lb=document.getElementById("lang");if(lb)lb.textContent=(lang==="nl"?"EN":"NL");if(window.POST)window.POST();}window.repaint=paint;document.addEventListener("click",function(e){if(e.target.closest("#lang")){setLang(lang==="nl"?"en":"nl");paint();}});paint();}
